// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protofiles/proposal.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProposeClient is the client API for Propose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProposeClient interface {
	MakeProposal(ctx context.Context, in *Proposal, opts ...grpc.CallOption) (*Response, error)
}

type proposeClient struct {
	cc grpc.ClientConnInterface
}

func NewProposeClient(cc grpc.ClientConnInterface) ProposeClient {
	return &proposeClient{cc}
}

func (c *proposeClient) MakeProposal(ctx context.Context, in *Proposal, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protofiles.Propose/MakeProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProposeServer is the server API for Propose service.
// All implementations must embed UnimplementedProposeServer
// for forward compatibility
type ProposeServer interface {
	MakeProposal(context.Context, *Proposal) (*Response, error)
	mustEmbedUnimplementedProposeServer()
}

// UnimplementedProposeServer must be embedded to have forward compatible implementations.
type UnimplementedProposeServer struct {

}

func (UnimplementedProposeServer) MakeProposal(context.Context, *Proposal) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeProposal not implemented")
}
func (UnimplementedProposeServer) mustEmbedUnimplementedProposeServer() {}

// UnsafeProposeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProposeServer will
// result in compilation errors.
type UnsafeProposeServer interface {
	mustEmbedUnimplementedProposeServer()
}

func RegisterProposeServer(s grpc.ServiceRegistrar, srv ProposeServer) {
	s.RegisterService(&Propose_ServiceDesc, srv)
}

func _Propose_MakeProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposeServer).MakeProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.Propose/MakeProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposeServer).MakeProposal(ctx, req.(*Proposal))
	}
	return interceptor(ctx, in, info, handler)
}

// Propose_ServiceDesc is the grpc.ServiceDesc for Propose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Propose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.Propose",
	HandlerType: (*ProposeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeProposal",
			Handler:    _Propose_MakeProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/proposal.proto",
}
